config/routes.rb
Rails.application.routes.draw do

  Blog::Application.routes.draw do

  devise_for :users

    resources :posts do
      resources :comments
    end

    root "welcome#index"
  get 'persons/profile', as: 'user_root'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 2}
  validates :author, presence: true,
            length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!, :except => [:create]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]


  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:author, :title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<% if user_signed_in? %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong></strong>
      <%= comment.body %>
    </p>

    <p>
      <%= link_to 'Destroy Comment', [comment.post, comment],
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </p>

<% else %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong></strong>
      <%= comment.body %>
    </p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </p>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<% if user_signed_in? %>
    <%= link_to 'New post', new_post_path %><br>
    <span>Welcome, <%= current_user.email %></span>
    <%= link_to 'Exit', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Enter', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %>
<% end %>
<% if user_signed_in? %>
<table>
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td><%= post.author %></td>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<% else %>
    <table>
      <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>

      <% @posts.each do |post| %>
          <tr>
            <td><%= post.author %></td>
            <td><%= post.title %></td>
            <td><%= post.text %></td>
            <td><%= link_to 'Show', post_path(post) %></td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if user_signed_in? %>
    <span>Welcome, <%= current_user.email %></span>
    <%= link_to 'Exit', destroy_user_session_path, :method => :delete %><br>
<% else %>
    <%= link_to 'Enter', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %>
<% end %>

<% if user_signed_in? %>
    <p>
      <strong>Author:</strong>
      <%= @post.author %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= @post.text %>
    </p>

    <h2>Comments</h2>
    <%= render @post.comments %>

    <h2>Add a comment:</h2>
    <%= render "comments/form" %>

    <%= link_to 'Edit Post', edit_post_path(@post) %> |
    <%= link_to 'Back to Posts', posts_path %>

<% else %>
    <p>
      <strong>Author:</strong>
      <%= @post.author %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= @post.text %>
    </p>

    <h2>Comments</h2>
    <%= render @post.comments %>

    <h2>Add a comment:</h2>
    <%= render "comments/form" %>
    <%= link_to 'Back to Posts', posts_path %>
<% end %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <span>Welcome, <%= current_user.email %></span><br>
    <%= link_to "Watch blogs", controller: "posts" %><br>
    <%= link_to 'Exit', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to "My Blog", controller: "posts" %><br>
    <%= link_to 'Enter', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %>
<% end %>